#Include "Protheus.ch"

/*-----------------------------------------------------------------------------------*
| P.E.:  A680PERG                                                                    |
| Desc:  permite realizar a validação da pergunta									 |
| Nahim Terrazas 																	 |
| de Producción 06/03/2020															 |
*-----------------------------------------------------------------------------------*/


User Function A680PERG
	Local lRet := .T.
//	If !lRet := .F.EndIf
Return lRet