#Include "Protheus.ch"
#Include "Parmtype.ch"
#Include "Rwmake.ch"

/*
ÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜÜ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
ฑฑษออออออออออัออออออออออหอออออออัออออออออออออออออออออหออออออัอออออออออออออปฑฑ
ฑฑบPrograma  ณMT462MNU บAutor  ณNahim Terrazas    บ Data ณ  05/04/19   	  บฑฑ
ฑฑฬออออออออออุออออออออออสอออออออฯออออออออออออออออออออสออออออฯอออออออออออออนฑฑ
ฑฑ	Punto de entrada al hacer una anulaci๓n en la rutina FINA088		   ฑฑ
ฑฑ	Anulacion de cobros diversos 									      นฑฑ
ฑฑบUso       ณ BOLIVIA                                                      บฑฑ
ฑฑศออออออออออฯออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออผฑฑ
ฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑฑ
฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿฿
*/

User function FA088OK()
    Local aArea	:= GetArea()
    Local cTemp	:= getNextAlias()
    Local lRet	:= .T.
    if 'ANULAR' $ ccadastro
        lRet :=  MSGYESNO( "ฟEstแ seguro de que desea ANULAR la transacci๓n Seleccionada (no podrแ digitar el mismo nro de recibo nuevamente)?", "Confirmaci๓n" )
    else
        lRet :=  MSGYESNO( "ฟEstแ seguro de que desea BORRAR la transacci๓n Seleccionada ?", "Confirmaci๓n" )
    endif
    if !lRet
        return lRet
    endif

return lRet
