User Function OM200GRV()

	TRBPED->PED_UOBS :=  SC5->C5_UOBSERV
	TRBPED->PED_UNOMF :=  SC5->C5_UNOMCLI
	TRBPED->PED_UCOSEG := SA1->A1_CODSEG
	//If MV_PAR06 == 2
	TRBPED->PED_ULOCAL :=  SC9->C9_LOCAL //SC5->C5_UNOMCLI
	if NNR->(msSeek(xFilial('NNR') + SC9->C9_LOCAL))
		TRBPED->PED_ULOCAL :=  SC9->C9_LOCAL  +" - "+  NNR->NNR_DESCRI  //SC5->C5_UNOMCLI
	endif
	//	TRBPED->PED_ULOCAL :=  // SC9->C9_LOCAL //SC5->C5_UNOMCLI
	//endif

	MsUnlock()

Return Nil
