#include 'protheus.ch'
#include 'parmtype.ch'

user function RESLINGR()
	SELECT TAB.* FROM SA6010 SA6
	JOIN (SELECT

	'LINEA' TIPO,LIN.A6_NUMCON CODIGOINTERNO,
	MAX(SEH.EH_OPERAC) OPBANCO,MAX(ZEH_TAXA)'%COMIS',LIN.A6_UPRPRES '%COP',MAX(SEH.EH_TAXA) TASA,

	LIN.A6_UVLRLIN * (LIN.A6_UPRPRES/100) 'P_CAP_OPER',LIN.A6_UVLRLIN TOTAPROB,(LIN.A6_UVLRLIN * (LIN.A6_UPRPRES/100)) - LIN.A6_USLDOPE 'TOT_UTIL_PRES',
	LIN.A6_USLDLIN SALDOLINEA,LIN.A6_USINMU INMUEBLES,LIN.A6_USMYV+ LIN.A6_USVEI 'MAQ_VEHICULO',LIN.A6_USDPF+LIN.A6_USDASFA 'DPF_ASFALTO',
	LIN.A6_USINMU+LIN.A6_USMYV+ LIN.A6_USVEI+LIN.A6_USDPF+LIN.A6_USDASFA TOTALGARANT,A6_XCOD,A6_XAGENCI, A6_XNUMCON

	FROM SA6010 LIN
	LEFT JOIN SEH010 SEH ON EH_XCOD = LIN.A6_COD AND EH_XAGENCI = LIN.A6_AGENCIA AND EH_XNUMCON  = LIN.A6_NUMCON AND SEH.D_E_L_E_T_ ='' AND EH_TIPO = 'EMP' AND EH_ULINEA = '1'
	LEFT JOIN ZEH010 ZEH ON ZEH_BANCO = LIN.A6_COD AND ZEH_AGENCI = LIN.A6_AGENCIA AND ZEH_CONTA = LIN.A6_NUMCON AND ZEH.D_E_L_E_T_ =''
	WHERE LIN.D_E_L_E_T_ = '' AND LIN.A6_ULINEA = '1'
	GROUP BY LIN.A6_NUMCON,LIN.A6_UPRPRES,LIN.A6_UVLRLIN,LIN.A6_USLDOPE,LIN.A6_USLDLIN,LIN.A6_USINMU,LIN.A6_USMYV,LIN.A6_USVEI,
	LIN.A6_USDPF,LIN.A6_USDASFA,A6_XCOD,A6_XAGENCI, A6_XNUMCON
	)TAB ON A6_COD = TAB.A6_XCOD AND A6_AGENCIA = TAB.A6_XAGENCI AND A6_NUMCON = TAB.A6_XNUMCON

	WHERE SA6.D_E_L_E_T_ = ''
	UNION

	SELECT 'PRESTAMOFL' TIPO,EH_NUMERO CODIGOINTERNO,EH_OPERAC OPBANCO, 0 '%COMIS',100 '%COP',EH_TAXA TASA,
	EH_VALOR 'P_CAP_OPER', EH_VALOR TOTAPROB,EH_VALOR - EH_SALDO 'TOT_UTIL_PRES',
	0 SALDOLINEA,A6_USINMU INMUEBLES,A6_USMYV+ A6_USVEI 'MAQ_VEHICULO',A6_USDPF+A6_USDASFA 'DPF_ASFALTO',
	A6_USINMU+A6_USMYV+ A6_USVEI+A6_USDPF+A6_USDASFA TOTALGARANT,A6_XCOD,A6_XAGENCI, A6_XNUMCON

	FROM SA6010 SA6
	JOIN SEH010 PRES
	ON PRES.EH_BANCO = A6_COD AND PRES.EH_AGENCIA = A6_AGENCIA AND PRES.EH_CONTA  = A6_NUMCON
	AND PRES.EH_ULINEA <> '1' AND EH_TIPO = 'EMP' AND PRES.D_E_L_E_T_ =''
return